version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      turborepo:
        patterns:
          - 'turbo'
      typescript:
        patterns:
          - 'typescript'
          - '@types/*'
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      vite:
        patterns:
          - 'vite'
          - '@vitejs/*'
      tailwind:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
